# Get the script's directory
$PSScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path

# --- Modify total problem counts here ---
$TotalEasy = 350
$TotalMedium = 650
$TotalHard = 250
# ---------------------------------

# Initialize counters
$CompletedEasy = 0
$CompletedMedium = 0
$CompletedHard = 0

# Get all .md files in the directory
$allMarkdownFiles = Get-ChildItem -Path $PSScriptRoot -Filter "*.md" -File

# Loop through files and count based on frontmatter
foreach ($file in $allMarkdownFiles) {
    if ($file.Name -in @("README.md", "算法学习主控平台.md")) {
        continue
    }
    $fileContent = Get-Content -Path $file.FullName -TotalCount 10
    $difficultyMatch = $fileContent | Select-String -Pattern "(?i)^\s*difficulty:\s*(Easy|Medium|Hard)"
    if ($difficultyMatch) {
        $difficulty = $difficultyMatch.Matches[0].Groups[1].Value.Trim()
        if ($difficulty -eq "Easy") {
            $CompletedEasy++
        }
        elseif ($difficulty -eq "Medium") {
            $CompletedMedium++
        }
        elseif ($difficulty -eq "Hard") {
            $CompletedHard++
        }
    }
}

# Calculate total progress
$TotalCompleted = $CompletedEasy + $CompletedMedium + $CompletedHard
$TotalProblems = $TotalEasy + $TotalMedium + $TotalHard
$ProgressPercentage = if ($TotalProblems -gt 0) { [Math]::Round(($TotalCompleted / $TotalProblems * 100), 2) } else { 0 }

# Create the README content
$ReadmeContent = @"
# LeetCode Notes

Welcome to my LeetCode notes repository!

---

## Progress Overview

**Total Progress: $TotalCompleted / $TotalProblems ($($ProgressPercentage)%)**

| Difficulty | Completed | Total | Progress Bar |
| :----- | :---: | :---: | :--- |
| **Easy**   | $CompletedEasy   | $TotalEasy   | $( '🟩' * ([int]($CompletedEasy / $TotalEasy * 20)) )$( '⬜️' * (20 - [int]($CompletedEasy / $TotalEasy * 20)) ) |
| **Medium** | $CompletedMedium | $TotalMedium | $( '🟩' * ([int]($CompletedMedium / $TotalMedium * 20)) )$( '⬜️' * (20 - [int]($CompletedMedium / $TotalMedium * 20)) ) |
| **Hard**   | $CompletedHard   | $TotalHard   | $( '🟩' * ([int]($CompletedHard / $TotalHard * 20)) )$( '⬜️' * (20 - [int]($CompletedHard / $TotalHard * 20)) ) |

---

*This README was automatically generated by a script on $(Get-Date)*
"@

# Write content to README.md file
Set-Content -Path (Join-Path $PSScriptRoot "README.md") -Value $ReadmeContent -Encoding UTF8

Write-Host "README.md has been updated successfully."
